version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: muzika
      POSTGRES_USER: muzika_user
      POSTGRES_PASSWORD: muzika123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./Songs:/app/Songs

volumes:
  postgres-data: